# apiVersion: v1
# kind: PersistentVolumeClaim
# metadata:
#   name: pvc-nfs-storage
#   namespace: gitlab-managed-apps
#   labels:
#     app: grafana
# spec:
#   storageClassName: managed-nfs-storage
#   accessModes:
#     - ReadWriteMany
#   resources:
#     requests:
#       storage: 500Mi
